# Autoencoder configuration

ae:
  module:
    _target_: tbfm.ae.LinearChannelAE
    latent_dim: ${latent_dim}
    in_dim: 96
    warm_start: true

  sharing:
    is_shared: false
    lora_dim: 1

  training:
    loss_function: mse
    coadapt: true
    lr: 1e-4