# @package _global_
# Normalizing Flow Autoencoder configuration

ae:
  module:
    _target_: tbfm.flow_ae.FlowChannelAE
    latent_dim: ${latent_dim}
    in_dim: 96
    num_flow_layers: 4  # Number of coupling layers (more = more expressive)
    hidden_dim: 128     # Hidden layer width in coupling networks
    use_linear_projection: true  # Linear projection before flows
    use_lora: false     # LoRA adaptation (not yet implemented for flow AE)

  should_warm_start: true
  warm_start_is_identity: false

  dispatcher:
    _target_: tbfm.flow_ae.SessionDispatcherFlowAE

  sharing:
    is_shared: false

  training:
    coadapt: true  # If true, adapt in supervised manner after PCA warm-up
    optim:
      lr: 1e-4     # Slightly higher LR for flow models
      eps: 1e-8
      weight_decay: 0.0
      amsgrad: false
