# @package _global_
# TBFM (Temporal Basis Function Model) configuration

tbfm:
  module:
    _target_: tbfm.tbfm.TBFM
    in_dim: ${latent_dim}  # By default TBFM lives in a latent space.
    runway: ${data.runway}
    num_bases: 20
    trial_len: ${data.y_len}
    latent_dim: 16  # This is basis generator latent dim
    basis_depth: 3
    covariate_dim: ${covariate_dim}
    zscore: false
    use_meta_learning: true
    proj_meta_dim: 32
    basis_gen_dropout: 0.3
    embed_dim_rest: 3
    embed_dim_stim: 15

  sharing:
    shared: true

  dispatcher:
    _target_: tbfm.tbfm.SessionDispatcherTBFM

  # Learning parameters
  training:
    optim:
      lr_head: 4e-4
      lr_meta: 3e-3
      wd_head: 1e-4
      wd_meta: 1e-5
    lambda_fro: 45.0
    lambda_ortho: 0.00
