# @package _global_
# TBFM (Temporal Basis Function Model) configuration

tbfm:
  module:
    _target_: tbfm.tbfm.TBFM
    in_dim: ${latent_dim}  # By default TBFM lives in a latent space.
    runway: ${data.runway}
    num_bases: 17
    trial_len: ${data.y_len}
    latent_dim: 4
    basis_depth: 4
    covariate_dim: ${covariate_dim}
    zscore: false
    use_film_bases: true
    embed_dim_rest: 3
    embed_dim_stim: 29

  sharing:
    shared: true

  dispatcher:
    _target_: tbfm.tbfm.SessionDispatcherTBFM

  # Learning parameters
  training:
    optim:
      lr_head: 2e-4
      lr_film: 3e-3
      wd_head: 1e-4
      wd_film: 1e-5
    lambda_fro: 0.05
    lambda_ortho: 0.2
