# @package _global_
# Meta-learning configuration

meta:
  # Residual-based meta-learning (MAML-style)
  is_basis_residual: false  # If true, use low-rank residual mode: bases += W*f(embed_stim)
  basis_residual_rank: 5     # Rank of residual subspace
  residual_mlp_hidden: 16    # Hidden dimension for residual MLP
  
  training:
    coadapt: false  # If true, co-adapt embeddings with other parameters instead of inner loop
    embed_steps_per_other_step: 1  # How many embedding updates per other parameter updates
    inner_steps: 20
    support_size: 300
    lambda_l2: 1e-3
    optim:
      lr: 1e-2
      weight_decay: 1e-4
